version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: clinic_redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass clinic_redis_secret_732
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
